[pytest]
# Alamat server lokal yang digunakan sebagai basis pengujian UI Playwright
base_url = http://localhost:3000

# Opsi tambahan untuk menjalankan pengujian secara detail (verbose)
addopts = -v --headed
